Update README.md
DavidRisch/steamvr_utils pull request #17
Opened 2022-08-30 05:11 UTC by yaomtc

Added clarification.

2022-08-30 11:39 UTC, DavidRisch requested changes

2022-08-30 11:39 UTC, DavidRisch commented on README.md
> +cd ./steamvr-utils
The dash should be an underscore.

2022-08-30 15:08 UTC, yaomtc reviewed
EDIT: disregard

2022-08-30 15:08 UTC, yaomtc commented on README.md
> +cd ./steamvr-utils
Oops, thanks!

2022-09-01 20:29 UTC, DavidRisch approved these changes

2022-09-01 20:30 UTC, merged

2022-09-01 20:30 UTC, DavidRisch commented
Thanks for your contribution @yaomtc!